### ISSUE TITLE
example not work for me 

### ISSUE THREAD

**Issue by limweb** [alarner/bookshelf-api#7]
I'm use  node 6.2.0  win10     I'm test by you example   /api/v1/product is not work 
it say  Not Found 404

but in custom route is work app.get('/api/v1/product', api('Product'))

please help me  

Thanks.

**Comment by limweb** [comment]
win10  error in   path.sep   because    path.sep == '\'
I'm change to '/'  it work.

**Comment by alarner** [comment]
Should work now @limweb . Just re-published to npm. Thanks for the PR!
